version: '3.8'

services:
  postgres:
    image: postgres:14.19-alpine3.21
    container_name: test_postgres
    environment:
      POSTGRES_USER: ojeomneo
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: ojeomneo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

